### ISSUE TITLE
Superscript after index-style linking not rendering

### ISSUE THREAD

**Issue by calvinjuarez** [Orc/discount#120] opened 2015-03-17 21:39 UTC
``` markdown
[Link Text][index]^1
```

is compiling to

``` html
<a href="{indexURL}">Link Text</a>^1
```

rather than

``` html
<a href="{indexURL}">Link Text</a><sup>1</sup>
```

_I'm using Discount v2.1.5a via [CodeKit](https://github.com/bdkjones/CodeKit) v2.2._
# 
#### Update:

Even just `]^1` compiles to `]^1`, instead of `]<sup>1</sup>`.

The characters I've found this to be true for are:
- `[` & `]`
- `{` & `}`
- `(` (although `)` works)
- `_` & `*` (such as immediately after `**bold**` or `_italic_` text)
- ` `(space),`.`,`;`,`,`, &`&`
- Inlined HTML entities (e.g. `&copy;^1` → `©^1`, but `©^1` → `©<sup>1</sup>`)

**Comment by Orc** [comment] 2015-03-19 06:20
Ugh.  ^ is iffy;  it wants to cuddle up next to numbers, words or ')', and refuses to superscript if it can't.   Sorry -- it's not really good for any sort of proper mathy things :-(  I don't know if this should be described as broken by design or broken by complexity!

**Comment by calvinjuarez** [comment] 2015-03-19 11:03
Got it.  I've worked around it by just putting an actual zero width space character before it, which it seems to be okay with somehow.  :P  Guess it'll have to do for now.

**Comment by Orc** [comment] 2017-01-28 00:16
After looking at it for longer than I care to think about, I'm going to have mark this as broken by complexity.   I'll have to maintain a cache of the last non-markup character emitted and test that for being one of the things I can superscript against.

I'm not going to close the issue, but keep it in mind.   If I can easily maintain a cache and not have it freak out on me I should be able to fit it in before the next major release.

**Comment by Orc** [comment] 2017-01-28 20:01
Okay, I think I've found a minimally invasive way to make it work without making the rest of the code freak out.   I've checked in (and mirrored here) a changeset that uses a cache, so it's now properly handling things like `A[^B]`  (`-> A[^B]`),  `[A]^B` (`-> [A]^B`), `[A](C)^B` (`-> <a href="C">A</a><sup>B</sup>`) and `<span>A</span>^B` (`-> `<span>A</span><sup>B</sup>`.)

There are html block edge cases where this patch will produce hilariously wrong results  (embedding block elements in the middle of a line and following them with a superscript will incorrectly `<sup>` that superscript) but working around them falls into the category of ["**NO! WRONG! TOTALLY WRONG! WHERE'D YOU LEARN THIS? STOP DOING IT!**"](http://www.angryflower.com/247.html) and I don't know if discount can support that level of handholding without becoming insanely bloated and slow.

**Closed by Orc** 2017-01-28 20:01 UTC
